<table class="twelve columns">
    <tr>
        <td>
            <h1>Bonjour,</h1>
            <p class="lead">Votre demande de restauration de mot de passe a bien été prise en compte.</p>
            <p>Voici votre nouveau mot de passe : </p>
        </td>
        <td class="expander"></td>
    </tr>
</table>

<table class="twelve columns">
    <tr>
        <td class="panel center">
            <h1><?php echo $this->password; ?></h1>
        </td>
        <td class="expander"></td>
    </tr>
</table>